 Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: "2019-03-25T18:19:32Z"
  generation: 215
  labels:
    app: portal-intranet
  name: portal-intranet
  namespace: des-portal-intranet
  resourceVersion: "603346444"
  selfLink: /apis/apps.openshift.io/v1/namespaces/des-portal-intranet/deploymentconfigs/portal-intranet
  uid: 89b9367b-4f2a-11e9-9248-0050568f1a87
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: portal-intranet
    deploymentconfig: portal-intranet
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 1200
    resources: {}
    type: Recreate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: portal-intranet
        deploymentconfig: portal-intranet
    spec:
      containers:
      - env:
        - name: TZ
          value: America/Sao_Paulo
        - name: JAVA_OPTS_APPEND
          value: -DHOST="$(hostname)"
        - name: OPENSHIFT_DB_HOST
          value: orades01.ti.sabesp.com.br
        - name: OPENSHIFT_LIFERAY_DB_USR
          value: liferay
        - name: OPENSHIFT_LIFERAY_DB_PWD
          value: -6d21ae33cd063979
        - name: OPENSHIFT_DB_PORT
          value: "1521"
        - name: OPENSHIFT_DB_SERVICE_NAME
          value: desportalcorporativo
        image: docker-registry.default.svc:5000/des-portal-intranet/portal-intranet@sha256:c85d1c4f180a1b1217716a270aa5d6d48d6ce230b7436be345a507621a2ce0db
        imagePullPolicy: Always
        name: portal-intranet
        ports:
        - containerPort: 8009
          protocol: TCP
        - containerPort: 9990
          protocol: TCP
        - containerPort: 9999
          protocol: TCP
        - containerPort: 1099
          protocol: TCP
        - containerPort: 4447
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/data
          name: des-portal-intranet-rhsso-cert-volume
        - mountPath: /opt/eap/standalone/log
          name: des-portal-intranet-logs-volume
        - mountPath: /opt/liferay/data
          name: pv-des-portal-intranet
      dnsPolicy: ClusterFirst
      nodeSelector:
        nodeapp/des: "true"
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: des-portal-intranet-rhsso-cert-volume
        persistentVolumeClaim:
          claimName: pvc-des-portal-intranet-rhsso-cert
      - name: des-portal-intranet-logs-volume
        persistentVolumeClaim:
          claimName: pvc-des-portal-intranet-logs
      - name: pv-des-portal-intranet
        persistentVolumeClaim:
          claimName: pvc-des-portal-intranet
  test: false
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - portal-intranet
      from:
        kind: ImageStreamTag
        name: portal-intranet:latest
        namespace: des-portal-intranet
      lastTriggeredImage: docker-registry.default.svc:5000/des-portal-intranet/portal-intranet@sha256:c85d1c4f180a1b1217716a270aa5d6d48d6ce230b7436be345a507621a2ce0db
    type: ImageChange
  - type: ConfigChange
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-07-26T19:07:35Z"
    lastUpdateTime: "2023-07-26T19:07:35Z"
    message: Deployment config has minimum availability.
    status: "True"
    type: Available
  - lastTransitionTime: "2023-07-26T19:06:51Z"
    lastUpdateTime: "2023-07-26T19:07:36Z"
    message: replication controller "portal-intranet-119" successfully rolled out
    reason: NewReplicationControllerAvailable
    status: "True"
    type: Progressing
  details:
    causes:
    - imageTrigger:
        from:
          kind: DockerImage
          name: docker-registry.default.svc:5000/des-portal-intranet/portal-intranet@sha256:c85d1c4f180a1b1217716a270aa5d6d48d6ce230b7436be345a507621a2ce0db
      type: ImageChange
    message: image change
  latestVersion: 119
  observedGeneration: 215
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1
