apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs1
spec:
  capacity:
    storage: 1Gi 
  accessModes:
  - ReadWriteMany 
  nfs: 
    path: /export/nfs1 
    server: 192.168.38.130 
  persistentVolumeReclaimPolicy: Retain 