apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-backup
  labels:
    app: ubuntu
spec:
  accessModes:
    - ReadWriteMany
  storageClassName : ""
  resources:
    requests:
      storage: 50Mi
  volumeName: pv-nfs-backup