apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  volumes:
  - name: nfs
    persistentVolumeClaim:
      claimName: pvc-nfs
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: ["/bin/sleep", "3650d"]
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: nfs
      mountPath: /mnt/nfs1
  restartPolicy: Always
  