apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  volumes:
  - name: des-portal-intranet-rhsso-cert-volume
    persistentVolumeClaim:
      claimName: pvc-des-portal-intranet-rhsso-cert
  - name: des-portal-intranet-logs-volume
    persistentVolumeClaim:
      claimName: pvc-des-portal-intranet-logs
  - name: pv-des-portal-intranet
    persistentVolumeClaim:
      claimName: pvc-des-portal-intranet
  containers:
  - name: ubuntu
    image: daoki01/ubuntutools:latest
    command: ["/bin/sleep", "3650d"]
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /opt/data
      name: des-portal-intranet-rhsso-cert-volume
    - mountPath: /opt/eap/standalone/log
      name: des-portal-intranet-logs-volume
    - mountPath: /opt/liferay/data
      name: pv-des-portal-intranet
  restartPolicy: Always
  