apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  volumes:
  - name: nfs1
    persistentVolumeClaim:
      claimName: pvc-nfs1
  - name: nfs2
    persistentVolumeClaim:
      claimName: pvc-nfs2
  containers:
  - name: ubuntu
    image: daoki01/ubuntutools:latest
    command: ["/bin/sleep", "3650d"]
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: nfs1
      mountPath: /mnt/nfs1
    - name: nfs2
      mountPath: /mnt/nfs2
  restartPolicy: Always
  